### ISSUE TITLE
[feat]: Make workflow to publish with gh-pages

### ISSUE THREAD

**Issue by srealmoreno** [srealmoreno/react-project-template#5]
### Feature description

Make workflow to publish with gh-pages

### Related Code

```yml
name: 🚀 Deploy to GitHub Pages

on:
  push:
    paths: [src/**, package.json, tsconfig.json, package-lock.json]
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3

      - name: 🚀 Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build
        run: npm run build

      - name: 🚀 Setup Pages
        uses: actions/configure-pages@v3

      - name: ⤴️ Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

```

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/{{username}}/{{repo}}/blob/main/docs/CONTRIBUTING.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/{{username}}/{{repo}}/blob/main/docs/CODE_OF_CONDUCT.md).
